Projeto feito por: Anderson Rangel<br>
Data: 24/04/26<br>
Objetivo: Me ajudar com análises financeiras práticas e intuitivas.

<h2>Sobre o projeto</h2>
<p>Este código em Python visa transformar tabelas Excel de gastos mensais e anuais em gráficos visuais para melhor visualizção e compreensão. Facilitando a comparação do meu histórico de gastos e deste modo, me auxiliando no progresso da minha vida financeira.<br>
Obs: será feito passo a passo o código para auxiliar a compreensão.</p>

In [3]:
# Passo 1: importar a tabela.

import pandas as pd

tabela = pd.read_excel("Gastos Totais Gerais 2026-2028.xlsx")
display(tabela)

     Ano        Mês  Gastos Fixos  Gastos Variáveis  Gasto Total
0   2026    Janeiro        883.23             695.6      1578.83
1   2026  Fevereiro        883.23             710.0      1593.23
2   2026      Março        883.23             680.5      1563.73
3   2026      Abril        883.23             725.0      1608.23
4   2026       Maio        883.23             700.0      1583.23
5   2026      Junho        883.23             740.8      1624.03
6   2026      Julho        883.23             715.3      1598.53
7   2026     Agosto        883.23             690.0      1573.23
8   2026   Setembro        883.23             705.4      1588.63
9   2026    Outubro        883.23             730.0      1613.23
10  2026   Novembro        883.23             750.0      1633.23
11  2026   Dezembro        883.23             820.0      1703.23
12  2027    Janeiro        910.00             710.0      1620.00
13  2027  Fevereiro        910.00             725.0      1635.00
14  2027      Março        910.00             695.0      1605.00
15  2027      Abril        910.00             740.0      1650.00
16  2027       Maio        910.00             715.0      1625.00
17  2027      Junho        910.00             755.0      1665.00
18  2027      Julho        910.00             730.0      1640.00
19  2027     Agosto        910.00             705.0      1615.00
20  2027   Setembro        910.00             720.0      1630.00
21  2027    Outubro        910.00             745.0      1655.00
22  2027   Novembro        910.00             765.0      1675.00
23  2027   Dezembro        910.00             850.0      1760.00
24  2028    Janeiro        940.00             730.0      1670.00
25  2028  Fevereiro        940.00             745.0      1685.00
26  2028      Março        940.00             715.0      1655.00
27  2028      Abril        940.00             760.0      1700.00
28  2028       Maio        940.00             735.0      1675.00
29  2028      Junho        940.00             775.0      1715.00
30  2028      Julho        940.00             750.0      1690.00
31  2028     Agosto        940.00             725.0      1665.00
32  2028   Setembro        940.00             740.0      1680.00
33  2028    Outubro        940.00             765.0      1705.00
34  2028   Novembro        940.00             785.0      1725.00
35  2028   Dezembro        940.00             880.0      1820.00

In [4]:
# Passo 2: Tratar e preparar a tabela para o gráfico. Transformando as palavras em números.

from sklearn.preprocessing import LabelEncoder

# coluna Despesas Fixas
print("Valores únicos na coluna Mês antes do LabelEncoder:")
print(tabela["Mês"].unique())
print("Tipo da coluna Mês:", tabela["Mês"].dtype)

codificador_mes = LabelEncoder()
tabela["Mês_Encoded"] = codificador_mes.fit_transform(tabela["Mês"])

print("Valores únicos após o LabelEncoder:")
print(tabela["Mês_Encoded"].unique())

display(tabela)

Valores únicos na coluna Mês antes do LabelEncoder:
['Janeiro' 'Fevereiro' 'Março' 'Abril' 'Maio' 'Junho' 'Julho' 'Agosto'
 'Setembro' 'Outubro' 'Novembro' 'Dezembro']
Tipo da coluna Mês: object
Valores únicos após o LabelEncoder:
[ 4  3  8  0  7  6  5  1 11 10  9  2]

     Ano        Mês  Gastos Fixos  Gastos Variáveis  Gasto Total  Mês_Encoded
0   2026    Janeiro        883.23             695.6      1578.83            4
1   2026  Fevereiro        883.23             710.0      1593.23            3
2   2026      Março        883.23             680.5      1563.73            8
3   2026      Abril        883.23             725.0      1608.23            0
4   2026       Maio        883.23             700.0      1583.23            7
5   2026      Junho        883.23             740.8      1624.03            6
6   2026      Julho        883.23             715.3      1598.53            5
7   2026     Agosto        883.23             690.0      1573.23            1
8   2026   Setembro        883.23             705.4      1588.63           11
9   2026    Outubro        883.23             730.0      1613.23           10
10  2026   Novembro        883.23             750.0      1633.23            9
11  2026   Dezembro        883.23             820.0      1703.23            2
12  2027    Janeiro        910.00             710.0      1620.00            4
13  2027  Fevereiro        910.00             725.0      1635.00            3
14  2027      Março        910.00             695.0      1605.00            8
15  2027      Abril        910.00             740.0      1650.00            0
16  2027       Maio        910.00             715.0      1625.00            7
17  2027      Junho        910.00             755.0      1665.00            6
18  2027      Julho        910.00             730.0      1640.00            5
19  2027     Agosto        910.00             705.0      1615.00            1
20  2027   Setembro        910.00             720.0      1630.00           11
21  2027    Outubro        910.00             745.0      1655.00           10
22  2027   Novembro        910.00             765.0      1675.00            9
23  2027   Dezembro        910.00             850.0      1760.00            2
24  2028    Janeiro        940.00             730.0      1670.00            4
25  2028  Fevereiro        940.00             745.0      1685.00            3
26  2028      Março        940.00             715.0      1655.00            8
27  2028      Abril        940.00             760.0      1700.00            0
28  2028       Maio        940.00             735.0      1675.00            7
29  2028      Junho        940.00             775.0      1715.00            6
30  2028      Julho        940.00             750.0      1690.00            5
31  2028     Agosto        940.00             725.0      1665.00            1
32  2028   Setembro        940.00             740.0      1680.00           11
33  2028    Outubro        940.00             765.0      1705.00           10
34  2028   Novembro        940.00             785.0      1725.00            9
35  2028   Dezembro        940.00             880.0      1820.00            2

In [14]:
# Passo 3: Melhorar visualização usando o plotly.

import plotly.express as px
import plotly.graph_objects as go
# Criando o gráfico de barras
grafico_um = px.histogram(data_frame=tabela, x="Gasto Total", y="Mês", text_auto=True)
grafico_um.show()

grafico_dois = px.histogram(data_frame=tabela, x="Ano", y="Gasto Total", text_auto=True)
grafico_dois.show()

grafico_tres = px.histogram(data_frame=tabela, x="Mês", y="Gasto Total", color="Ano", text_auto=True)
grafico_tres.show()

#Gráfico de Pizza 1
labels = tabela["Ano"]
values = tabela["Gasto Total"]

# Criando o gráfico de pizza
fig_um = go.Figure(data=[go.Pie(labels=labels, values=values, textinfo='value')])

# Mostrando o gráfico
fig_um.show()

# Gráfico de Pizza 2
labels = tabela["Ano"]
values = tabela["Gastos Fixos"]

# Criando o gráfico de pizza
fig_dois = go.Figure(data=[go.Pie(labels=labels, values=values, textinfo='value')])

# Mostrando o gráfico
fig_dois.show()

# Gráfico de Pizza 3
labels = tabela["Ano"]
values = tabela["Gastos Variáveis"]

# Criando o gráfico de pizza
fig_tres = go.Figure(data=[go.Pie(labels=labels, values=values, textinfo='value')])

# Mostrando o gráfico
fig_tres.show()